### ISSUE TITLE
__gnu_cxx::new_allocator<IR::ValueType>::allocate(unsigned long, void const*) parsing running wasm file causing crash

### ISSUE THREAD

**Issue by zhongyinglou** [AndrewScheidecker/WAVM#100]
[__gnu_cxxnew_allocatorIRValueTypeallocate(unsigned long, void const) cauing crash3_7.zip](https://github.com/AndrewScheidecker/WAVM/files/2232089/__gnu_cxxnew_allocatorIRValueTypeallocate.unsigned.long.void.const.cauing.crash3_7.zip)

**Comment by AndrewScheidecker** [comment]
Thanks, this is fixed by https://github.com/AndrewScheidecker/WAVM/commit/88901f515facaf3698af9a6b53aef30322ae52c8

**Comment by zhongyinglou** [comment]
This vulnerability found by security researcher limingzheng From China Beijing Chainsguard (www.chainsguard.com) .
