### ISSUE TITLE
build on OSX, get error: use of undeclared identifier 'WAVM_DEBUG'

### ISSUE THREAD

**Issue by vchengsong** [AndrewScheidecker/WAVM#104]
WAVM$  cmake .
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- The ASM compiler identification is AppleClang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/song/Home/Golang/src/github.com/AndrewScheidecker/WAVM
WAVM$  ll
total 136
-rw-r--r--   1 song  staff  16178  8 18 20:00 CMakeCache.txt
drwxr-xr-x  15 song  staff    480  8 18 20:00 CMakeFiles
-rw-r--r--   1 song  staff   5703  8 18 19:53 CMakeLists.txt
-rw-r--r--   1 song  staff    718  8 18 20:00 CTestTestfile.cmake
drwxr-xr-x  11 song  staff    352  8 18 19:53 Include
-rw-r--r--   1 song  staff   1813  8 18 19:53 LICENSE
-rw-r--r--   1 song  staff  15369  8 18 20:00 Makefile
-rw-r--r--   1 song  staff   5211  8 18 19:53 README.md
drwxr-xr-x  13 song  staff    416  8 18 19:53 Source
drwxr-xr-x   9 song  staff    288  8 18 19:53 Test
drwxr-xr-x   6 song  staff    192  8 18 19:53 afl
drwxr-xr-x   2 song  staff     64  8 18 20:00 bin
-rw-r--r--   1 song  staff   3169  8 18 20:00 cmake_install.cmake
-rw-r--r--   1 song  staff    100  8 18 19:53 run-clang-format.sh
-rwxr-xr-x   1 song  staff   1312  8 18 19:53 travis-build.sh
WAVM$  make
Scanning dependencies of target WAVMUnwind
[  1%] Building CXX object Source/ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/libunwind.cpp.o
[  2%] Building C object Source/ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/Unwind-sjlj.c.o
[  3%] Building C object Source/ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindLevel1-gcc-ext.c.o
[  4%] Building C object Source/ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindLevel1.c.o
[  6%] Building ASM object Source/ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersRestore.S.o
[  7%] Building ASM object Source/ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersSave.S.o
[  8%] Building CXX object Source/ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/Unwind_AppleExtras.cpp.o
[  9%] Building CXX object Source/ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/Unwind-EHABI.cpp.o
[ 11%] Linking CXX shared library libWAVMUnwind.dylib
[ 11%] Built target WAVMUnwind
Scanning dependencies of target Platform
[ 12%] Building CXX object Source/Platform/CMakeFiles/Platform.dir/POSIX.cpp.o
[ 13%] Building ASM object Source/Platform/CMakeFiles/Platform.dir/POSIX.S.o
[ 14%] Linking CXX shared library libPlatform.dylib
ld: warning: could not create compact unwind for _forkedStackTrampoline: does not use RBP or RSP based frame
[ 14%] Built target Platform
Scanning dependencies of target Logging
[ 16%] Building CXX object Source/Logging/CMakeFiles/Logging.dir/Logging.cpp.o
/Users/song/Home/Golang/src/github.com/AndrewScheidecker/WAVM/Source/Logging/Logging.cpp:14:3: error: use of undeclared identifier 'WAVM_DEBUG'
        {WAVM_DEBUG != 0},
         ^
1 error generated.
make[2]: *** [Source/Logging/CMakeFiles/Logging.dir/Logging.cpp.o] Error 1
make[1]: *** [Source/Logging/CMakeFiles/Logging.dir/all] Error 2
make: *** [all] Error 2

**Comment by AndrewScheidecker** [comment]
This is a bug, but I think you can work around it by passing `-DCMAKE_BUILD_TYPE=RelWithDebInfo` to cmake.

**Comment by AndrewScheidecker** [comment]
This should be fixed by https://github.com/AndrewScheidecker/WAVM/commit/9d28bdc2375423d83306376cad9f5d98dd9fe1c3, please let me know if you still see it.
