### ISSUE TITLE
Clang/LLVM 3.8

### ISSUE THREAD

**Issue by upcFrost** [AndrewScheidecker/WAVM#52]
Hi, can you plz check the build against LLVM 3.8? On travis you're running the build with Clang 3.4.0 while linking everything to LLVM 3.8, which is a bit strange.

I'm getting a huge amount of errors with the latest GCC, as well as with Clang 3.8.2.

**Comment by AndrewScheidecker** [comment]
I fixed some errors in `SExpression.cpp` and updated Travis CI to use the gcc-5 and clang-3.8 compilers from apt (GCC 5.4.1 and clang 3.8.1). Please reopen if you're still seeing compile errors.
