### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by rongjiecomputer** [AndrewScheidecker/WAVM#53]
I built WAVM with Visual Studio 2015 and LLVM 4.0.

Running `wavm` with any test causes program crash with no console output even when `-d` is set.  GDB reports `Thread 1 received signal SIGSEGV, Segmentation fault.`

Running `Test Test\wast\helloworld.wast` gives the following error message.

```
Test\wast\helloworld.wast:3:2: missing import module="env" export="_fwrite" type="func (i32,i32,i32,i32)->i32"
(module
 ^
Test\wast\helloworld.wast:3:2: missing import module="env" export="memory" type="memory"
(module
 ^
Test\wast\helloworld.wast:3:2: missing import module="env" export="_stdout" type="immutable i32"
(module
 ^
Test\wast\helloworld.wast: testing failed!
```

Build log: `https://ci.appveyor.com/project/rongjiecomputer/wavm/build/1.0.17`

**Comment by AndrewScheidecker** [comment]
I verified that with the latest code I can't reproduce the crash or the error messages running `helloworld.wast`.

The build log looks ok.

Do `Assemble` and `Disassemble` work?

Can you try a Debug or RelWithDebInfo build, and run it in the debugger to see exactly where it's crashing?

**Comment by rongjiecomputer** [comment]
`Assemble` and `Disassemble` work just fine.

When I ran `wavm.exe` in debugger, debugger got stuck at a `std::string` function (from MSVC internal `xstring`). I tried to step in/out/over, nothing works. I have to abort debugging process to get out.

```
	_Myt& assign(const _Myt& _Right, const size_type _Roff, size_type _Count = npos)
		{	// assign _Right [_Roff, _Roff + _Count)
		_Right._Check_offset(_Roff); // <------- Stuck at here
```

Anymore idea?

**Comment by rongjiecomputer** [comment]
Can you download my [build artifact](https://ci.appveyor.com/project/rongjiecomputer/wavm/build/1.0.16/artifacts) and test with helloworld.wast? Or can pack your executables for me to compare?

**Comment by AndrewScheidecker** [comment]
I can reproduce the crash with your build (running `wavm helloworld.wast`), but it doesn't have debug info so it's hard to tell what's going on.

I suspect the problem is some incompatibility with your LLVM build. Are you building it yourself, or using something prebuilt? I build LLVM locally.

**Comment by rongjiecomputer** [comment]
I am using prebuilt LLVM provided by someone else.

I updated the build script, PDB and binaries can be found [here](https://ci.appveyor.com/project/rongjiecomputer/wavm/build/1.0.20/artifacts), though I don't have PDB for LLVM so it might be impossible to find anything useful.

**Comment by AndrewScheidecker** [comment]
Using those binaries with PDB, the callstack is in some STL code called by LLVM. I think the problem is likely that LLVM was compiled with a different STL than WAVM. Building LLVM with the same version of VS2015 should solve the problem.

**Comment by rongjiecomputer** [comment]
Thanks for taking your time to do all the debugging. Looks like I have no choice other than building LLVM myself.
