### ISSUE TITLE
use llvm 5

### ISSUE THREAD

**Issue by wanderer** [AndrewScheidecker/WAVM#60]
It would be nice to support llvm v5

**Comment by AndrewScheidecker** [comment]
Yeah. I haven't tried it yet, but I expect the hardest part to be updating the Travis CI scripts.

**Comment by AndrewScheidecker** [comment]
I made [a branch](https://github.com/AndrewScheidecker/WAVM/tree/llvm5) with the changes necessary to use LLVM 5.0, but it doesn't pass Travis CI yet because the binary distribution of LLVM 5 apparently needs OS X 10.13, but Travis CI only supports up to 10.12.

**Comment by AndrewScheidecker** [comment]
I decided to go ahead with the [upgrade to LLVM5](https://github.com/AndrewScheidecker/WAVM/commit/a64b79673fdff87de126ccda87c0203ebe5d48f2), and just disable the Travis OS X builder until the OS X version issue is fixed.
