### ISSUE TITLE
Support for LLVM 6 (tip-of-tree)

### ISSUE THREAD

**Issue by sbc100** [AndrewScheidecker/WAVM#62]
I wanted to check out WAVM, and I currently work on LLVM tip-of-tree, so that is the version I have handy (6.0.0svn).  Would supporting that be hard?   Maybe it would be useful to have an llvm-next branch to allow for staging updrades?

Maybe I'm just being lazy and should just build another copy of the LLVM locally.. ?

**Comment by AndrewScheidecker** [comment]
https://github.com/AndrewScheidecker/WAVM/commit/30edae6ae678c6dad76c97eec32edf704c7675c2 should support both LLVM 5 and 6.
