### ISSUE TITLE
Use of backtrace() in signal handler dangerous

### ISSUE THREAD

**Issue by spoonincode** [AndrewScheidecker/WAVM#80]
It's unsafe to use backtrace() in a signal handler.
https://www.gnu.org/software/libc/manual/html_node/Backtraces.html

**Comment by spoonincode** [comment]
>Yes, this works in practice, but is theoretically fragile

Unfortunately it appears it was not working in practice over here in our use
https://github.com/EOSIO/eos/
Saw lots of weird failures nearly immediately after SEGV handling. Weird SEGVs after returning, messages about malloc corruption, double frees, etc. So far removing the backtrace() call has cleared it all up. IMO signal handlers are something that needs to be done by the book; there is way too much opportunity for flaky behavior otherwise.

>The signal handler also calls isAddressOwnedByMemory/isAddressOwnedByTable

Isn't this done after returning from the signal handler? After the longjmp?

**Comment by AndrewScheidecker** [comment]
> So far removing the backtrace() call has cleared it all up.

Ok, maybe I'll remove the `backtrace` call for now.

> Isn't this done after returning from the signal handler? After the longjmp?

It used to be, but the latest code lets the runtime hook the signal handler to support "pure WASM" threads that don't call `catchSignals`.

**Comment by AndrewScheidecker** [comment]
I removed the `backtrace` call in [this commit](https://github.com/AndrewScheidecker/WAVM/commit/ba12feb1104e4ad0cf8e6e65b42c345e8d96880d). I'll leave this issue open to track replacing it with `libunwind`.

**Comment by AndrewScheidecker** [comment]
[This commit](https://github.com/AndrewScheidecker/WAVM/commit/c755d8fc2eb184b5c32080412cd4542855ba3658) uses LLVM's libunwind implementation for signal-safe backtraces on POSIX systems (tested on Linux and OSX).
