### ISSUE TITLE
Tests failing to execute with access violation

### ISSUE THREAD

**Issue by vincaslt** [AndrewScheidecker/WAVM#85]
I may be doing something wrong here, but when I try torun "echo.wast" or "helloworld.wast" tests they are crashing and throw some access violation error:

```
wavm .\helloworld.wast
Unhandled runtime exception: access violation
Call stack:
  Emscripten::instantiate
  run
  main
  invoke_main
  __scrt_common_main_seh
  __scrt_common_main
  mainCRTStartup
  BaseThreadInitThunk
  RtlUserThreadStart
```

this has likely started happening after the fix for: #83 

It works fine with this commit:

```
commit fae4a65846b4288adc85616a540b8b3d0f985d91
Author: Andrew Scheidecker <andrew@scheidecker.net>
Date:   Thu Apr 19 10:36:39 2018 -0400

    Fix compile error on older Clang versions
```

**Comment by AndrewScheidecker** [comment]
Should be fixed by this commit: https://github.com/AndrewScheidecker/WAVM/commit/45e8c8eca10cafc5d736ff49ea1d8a9abaa6f774
