### ISSUE TITLE
Compile to .bc file error on "clang --target=wasm32..."

### ISSUE THREAD

**Issue by eoline7** [AndrewScheidecker/WAVM#86]
I have a simple code:
```
  #include <stdio.h>
  int main() { printf("Hello World!\n"); return 0; }
```
Its Ok to compile, like this `clang hello.cpp -c -O3 -emit-llvm -o hello.bc`
But a error occurred after adding the param `--target=wasm32`
```
hello.cpp:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
```
What's the matter？How to do, please

**Comment by AndrewScheidecker** [comment]
I'm closing this as it's not a WAVM issue, but your problem is because clang doesn't come with a C standard library for the wasm32 target. You need to use clang as part of Emscripten or a similar toolchain.
