### ISSUE TITLE
Why do root objects keep reference counts?

### ISSUE THREAD

**Issue by vincaslt** [AndrewScheidecker/WAVM#87]
I've been looking through the code, and I can't figure out why `Runtime::ObjectImpl` has reference count? From what I see this is only used to determine if root objects are reachable, because non-root objects will always have their counts zero.

Would it not be better to maintain a list of rootObjects along with allObjects and instead of adding an overhead on every object created in the program? Are there any cases where root will have more than one reference, and it still wouldn't be possible to tell if it is alive or not?

**Comment by AndrewScheidecker** [comment]
Correct: the reference count is just used to find roots. Reference counting can't be used in general, as there may be cycles: for example a ModuleInstance -> TableInstance -> FunctionInstance -> ModuleInstance.

The reason I use reference counting is that it's very simple even when you have multiple threads that are creating and destroying root references. It also doesn't require global knowledge of other possible root references to an object to correctly maintain the root set.

The memory used by the reference count is really not worth worrying about. For example, `GlobalInstance` is the smallest object that has a reference count, and in that case the reference count would be 8/56 bytes, not counting memory allocated for the global in each Context in the same Compartment.

**Comment by vincaslt** [comment]
Yeah, you may have a point about the memory overhead, as it's usually only a problem when small structs in arrays (int32?) start having references to them. I'm not suggesting using the refcount, you'd still need to sweep periodically to clear cycles anyway.
