### ISSUE TITLE
loadModule(char const*, IR::Module&) parsing wast file causing  heap-buffer-overflow

### ISSUE THREAD

**Issue by zhongyinglou** [AndrewScheidecker/WAVM#92]
loadModule(char const*, IR::Module&) parsing wast file causing  heap-buffer-overflow
leading possible local code exec
[loadModule-heapbufferoverflow.zip](https://github.com/AndrewScheidecker/WAVM/files/2216042/loadModule-heapbufferoverflow.zip)

**Comment by AndrewScheidecker** [comment]
Thank you for the report. I've fixed the bug in https://github.com/AndrewScheidecker/WAVM/commit/2173c468a0f2f7227e6683b7a005cbec4cb5532b
