### ISSUE TITLE
IR::FunctionValidationContext::catch_all(IR::NoImm) heap-buffer-overflow parsing running wasm file causing crash 

### ISSUE THREAD

**Issue by zhongyinglou** [AndrewScheidecker/WAVM#93]
Hello Reporting some possible vul @WebAssembly Virtual Machine

Vul Description:
IR::FunctionValidationContext::catch_all(IR::NoImm) heap-buffer-overflow parsing running wasm file causing crash 

Impact Products version:
the latest wavm lib 

git log --pretty=oneline
commit 2173c468a0f2f7227e6683b7a005cbec4cb5532b

crash detail:
=================================================================

=================================================================
==24366==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x604000007478 at pc 0x0000004d42a9 bp 0x7ffde0436550 sp 0x7ffde0435d00
READ of size 8 at 0x604000007478 thread T0
    #0 0x4d42a8 in __asan_memcpy /local/mnt/workspace/clang_nightly/plain/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:23:3
    #1 0x7f4fb18eb7d7 in IR::FunctionValidationContext::catch_all(IR::NoImm) (/home/limingzheng/WAVM/build_debugclangasan/Source/IR/libIR.so+0x11c7d7)
    #2 0x7f4fb1887ead in IR::CodeValidationStream::catch_all(IR::NoImm) (/home/limingzheng/WAVM/build_debugclangasan/Source/IR/libIR.so+0xb8ead)
    #3 0x7f4fb3dcc519 in WASM::serializeFunctionBody(Serialization::InputStream&, IR::Module&, IR::FunctionDef&) (/home/limingzheng/WAVM/build_debugclangasan/Source/WASM/libWASM.so+0xa7519)
    #4 0x7f4fb3ee2316 in void WASM::serializeCodeSection<Serialization::InputStream>(Serialization::InputStream&, IR::Module&)::{lambda(Serialization::InputStream&)#1}::operator()(Serialization::InputStream&) const (/home/limingzheng/WAVM/build_debugclangasan/Source/WASM/libWASM.so+0x1bd316)
    #5 0x7f4fb3ee1cc1 in void WASM::serializeSection<void WASM::serializeCodeSection<Serialization::InputStream>(Serialization::InputStream&, IR::Module&)::{lambda(Serialization::InputStream&)#1}>(Serialization::InputStream&, WASM::SectionType, void WASM::serializeCodeSection<Serialization::InputStream>(Serialization::InputStream&, IR::Module&)::{lambda(Serialization::InputStream&)#1}) (/home/limingzheng/WAVM/build_debugclangasan/Source/WASM/libWASM.so+0x1bccc1)
    #6 0x7f4fb3e1d915 in void WASM::serializeCodeSection<Serialization::InputStream>(Serialization::InputStream&, IR::Module&) (/home/limingzheng/WAVM/build_debugclangasan/Source/WASM/libWASM.so+0xf8915)
    #7 0x7f4fb3dce589 in WASM::serializeModule(Serialization::InputStream&, IR::Module&) (/home/limingzheng/WAVM/build_debugclangasan/Source/WASM/libWASM.so+0xa9589)
    #8 0x7f4fb3dce97c in WASM::serialize(Serialization::InputStream&, IR::Module&) (/home/limingzheng/WAVM/build_debugclangasan/Source/WASM/libWASM.so+0xa997c)
    #9 0x511845 in loadBinaryModule(std::string const&, IR::Module&) (/home/limingzheng/WAVM/build_debugclangasan/bin/wavm+0x511845)
    #10 0x509409 in loadModule(char const*, IR::Module&) (/home/limingzheng/WAVM/build_debugclangasan/bin/wavm+0x509409)
    #11 0x50632c in run(CommandLineOptions const&) (/home/limingzheng/WAVM/build_debugclangasan/bin/wavm+0x50632c)
    #12 0x505a4c in main (/home/limingzheng/WAVM/build_debugclangasan/bin/wavm+0x505a4c)
    #13 0x7f4fafb4eb34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
    #14 0x434aa1 in _start (/home/limingzheng/WAVM/build_debugclangasan/bin/wavm+0x434aa1)

0x604000007478 is located 7 bytes to the right of 33-byte region [0x604000007450,0x604000007471)
allocated by thread T0 here:
    #0 0x501f32 in operator new(unsigned long) /local/mnt/workspace/clang_nightly/plain/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_new_delete.cc:92:3
    #1 0x7f4fb01c1c78 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (/lib64/libstdc++.so.6+0xbdc78)
    #2 0x7f4fb01c3967 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (/lib64/libstdc++.so.6+0xbf967)

SUMMARY: AddressSanitizer: heap-buffer-overflow /local/mnt/workspace/clang_nightly/plain/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:23:3 in __asan_memcpy
Shadow bytes around the buggy address:
  0x0c087fff8e30: fa fa fd fd fd fd fd fa fa fa 00 00 00 00 03 fa
  0x0c087fff8e40: fa fa fd fd fd fd fd fa fa fa 00 00 00 00 01 fa
  0x0c087fff8e50: fa fa fd fd fd fd fd fa fa fa 00 00 00 00 01 fa
  0x0c087fff8e60: fa fa fd fd fd fd fd fa fa fa 00 00 00 00 01 fa
  0x0c087fff8e70: fa fa fd fd fd fd fd fa fa fa 00 00 00 00 01 fa
=>0x0c087fff8e80: fa fa fd fd fd fd fd fa fa fa 00 00 00 00 01[fa]
  0x0c087fff8e90: fa fa 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  0x0c087fff8ea0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff8eb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff8ec0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff8ed0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==24366==ABORTING
  
  -------------------------------
[IRFunctionValidationContextcatch_all(IRNoImm)7_3.zip](https://github.com/AndrewScheidecker/WAVM/files/2232057/IRFunctionValidationContextcatch_all.IRNoImm.7_3.zip)

**Comment by zhongyinglou** [comment]
[IRFunctionValidationContextcatch_all(IRNoImm)7_3.zip](https://github.com/AndrewScheidecker/WAVM/files/2232045/IRFunctionValidationContextcatch_all.IRNoImm.7_3.zip)

**Comment by AndrewScheidecker** [comment]
Thanks, this is fixed by https://github.com/AndrewScheidecker/WAVM/commit/88901f515facaf3698af9a6b53aef30322ae52c8.

**Comment by zhongyinglou** [comment]
This vulnerability found by security researcher limingzheng From China Beijing Chainsguard (www.chainsguard.com) .
