### ISSUE TITLE
:FunctionValidationContext::else_(IR::NoImm) heap-buffer-overflow when parsing running wasm file causing crash 

### ISSUE THREAD

**Issue by zhongyinglou** [AndrewScheidecker/WAVM#94]
[IRFunctionValidationContextelse_(IRNoImm) 6_3.zip](https://github.com/AndrewScheidecker/WAVM/files/2232062/IRFunctionValidationContextelse_.IRNoImm.6_3.zip)

**Comment by AndrewScheidecker** [comment]
Thanks, this is fixed by https://github.com/AndrewScheidecker/WAVM/commit/88901f515facaf3698af9a6b53aef30322ae52c8.

**Comment by zhongyinglou** [comment]
This vulnerability found by security researcher limingzheng From China Beijing Chainsguard (www.chainsguard.com) .
