### ISSUE TITLE
IR::FunctionValidationContext::end(IR::NoImm)  heap-buffer-overflow parsing running wasm file causing crash

### ISSUE THREAD

**Issue by zhongyinglou** [AndrewScheidecker/WAVM#98]
[IRFunctionValidationContextend heapoverflow2_7.zip](https://github.com/AndrewScheidecker/WAVM/files/2232082/IRFunctionValidationContextend.heapoverflow2_7.zip)

**Comment by AndrewScheidecker** [comment]
Thanks, this is fixed by https://github.com/AndrewScheidecker/WAVM/commit/88901f515facaf3698af9a6b53aef30322ae52c8.

**Comment by zhongyinglou** [comment]
This vulnerability found by security researcher limingzheng From China Beijing Chainsguard (www.chainsguard.com) .
