### ISSUE TITLE
libRuntime.so!llvm::InstructionCombiningPass::runOnFunction(llvm::Function&) parsing running wasm file causing crash in runtime

### ISSUE THREAD

**Issue by zhongyinglou** [AndrewScheidecker/WAVM#99]
[InstructionCombiningPass_runOnFunction_crashin_libRuntime11_1.zip](https://github.com/AndrewScheidecker/WAVM/files/2232087/InstructionCombiningPass_runOnFunction_crashin_libRuntime11_1.zip)

**Comment by AndrewScheidecker** [comment]
Thanks, this is fixed by https://github.com/AndrewScheidecker/WAVM/commit/a0baaec170b55cc60cfe6bcc6b36add953a065d8

**Comment by zhongyinglou** [comment]
This vulnerability found by security researcher limingzheng From China Beijing Chainsguard (www.chainsguard.com) .
